import { useMemo, useState } from 'react';
import { AlertTriangle, CheckCircle2, LockKeyhole } from 'lucide-react';
import { approveTeamAliases, loginAliasAdmin, logoutAliasAdmin } from '../services/firebase';
import type { AliasReview } from '../types';

export function AliasApproval({ review }: { review: AliasReview }) {
  const candidates = useMemo(() => [...new Map(review.candidates.map((item) => [`${item.alias.toLowerCase()}=>${item.canonical.toLowerCase()}`, item])).values()], [review]);
  const [selected, setSelected] = useState(() => new Set<string>()); const [password, setPassword] = useState(''); const [loggedIn, setLoggedIn] = useState(false); const [busy, setBusy] = useState(false); const [done, setDone] = useState(false); const [error, setError] = useState('');
  const key = (alias: string, canonical: string) => `${alias.toLowerCase()}=>${canonical.toLowerCase()}`;
  const login = async () => { setBusy(true); setError(''); try { await loginAliasAdmin(password); setLoggedIn(true); setPassword(''); } catch { setError('Fel lösenord eller kontot saknas i Firebase Authentication.'); } finally { setBusy(false); } };
  const approve = async () => { const approved = candidates.filter((item) => selected.has(key(item.alias, item.canonical))); if (!approved.length) return; setBusy(true); setError(''); try { await approveTeamAliases(approved); await logoutAliasAdmin(); setDone(true); } catch { setError('Godkännandet kunde inte sparas. Kontrollera behörigheten.'); } finally { setBusy(false); } };
  if (done) return <div className="alias-review success"><CheckCircle2/><div><b>Namnvariationerna är godkända</b><p>Starta Firebase-workflowet manuellt i GitHub för att skapa raden med de nya aliasen.</p></div></div>;
  return <section className="alias-review"><AlertTriangle/><div className="alias-review-body"><small>Åtgärd krävs · kupong {review.roundDate}</small><h2>Kontrollera lagnamn</h2><p>Körningen hittade några få namn som kan avse samma lag. Godkänn endast par du känner igen.</p>{candidates.map((candidate) => { const id = key(candidate.alias, candidate.canonical); return <label className="alias-option" key={id}><input type="checkbox" checked={selected.has(id)} onChange={() => setSelected((current) => { const next = new Set(current); if (next.has(id)) next.delete(id); else next.add(id); return next; })}/><span><b>{candidate.alias}</b><i>är samma lag som</i><strong>{candidate.canonical}</strong><small>{candidate.source} · match {candidate.matchNumber}</small></span></label>; })}{!loggedIn ? <div className="alias-login"><LockKeyhole size={17}/><input aria-label="Lösenord" type="password" value={password} onChange={(event) => setPassword(event.target.value)} placeholder="Tipsgruppens lösenord"/><button disabled={busy || !password} onClick={login}>Logga in</button></div> : <button className="approve-button" disabled={busy || !selected.size} onClick={approve}>Godkänn valda namn</button>}{error && <p className="alias-error">{error}</p>}</div></section>;
}
