import { BarChart3, ExternalLink, Gem } from 'lucide-react';
import { SupportBars } from './SupportBars'; import { PublicDistribution } from './PublicDistribution'; import type { Match } from '../types';
const labels = { strong: ['🔥', 'Stark konsensus'], consensus: ['✓', 'Konsensus'], disagreement: ['!', 'Experterna är oense'], coverage: ['◈', 'Garderingskandidat'] } as const;
const sourceLabel = { rekatochklart: 'Rekatochklart', bettingstugan: 'Bettingstugan', understreckat: 'Understreckat', tipsmedoss: 'Tipsmedoss' } as const;
export function MatchCard({ match }: { match: Match }) {
  const label = labels[match.classification];
  const awaitingExperts = match.ballots.length === 0;
  const xStats = match.xStats?.entireSeason ?? match.xStats?.lastFiveGames;
  const xMetric = (name: 'xp' | 'xG' | 'xGC') => xStats?.metrics[name];
  const format = (value: number) => new Intl.NumberFormat('sv-SE', { maximumFractionDigits: 2 }).format(value);
  return <article className={`match-card ${match.classification}`}><div className="match-top"><span>Match {String(match.matchNumber).padStart(2, '0')}</span><span className={`badge ${match.classification}`}>{awaitingExperts ? 'Svenska Spels kupong' : `${label[0]} ${label[1]}${match.consensusSign ? ` · ${match.consensusSign}` : ''}`}</span></div><div className="teams"><div><strong>{match.homeTeam}</strong><small>Hemma</small></div><span>–</span><div><strong>{match.awayTeam}</strong><small>Borta</small></div></div>{!awaitingExperts && <><div className="ballots">{match.ballots.map((ballot) => <a href={ballot.sourceUrl} target="_blank" rel="noreferrer" key={ballot.expertId}><span>{ballot.expert}<small>{sourceLabel[ballot.source]}</small></span><b>{ballot.tip}</b><ExternalLink size={13}/></a>)}</div><div className="support-title"><span>Expertstöd</span><span>{match.ballots.length} röster</span></div><SupportBars support={match.support} experts={match.ballots.length}/></>}{match.publicDistribution && <PublicDistribution distribution={match.publicDistribution}/>} {xStats && <div className="xstats"><header><span><BarChart3 size={14}/> xStats · säsong</span><a href={match.xStats?.sourceUrl} target="_blank" rel="noreferrer">PlaymakerAI ↗</a></header><div>{(['xp', 'xG', 'xGC'] as const).map((name) => { const metric = xMetric(name); return metric && <section key={name}><b>{name === 'xp' ? 'xP' : name}</b><span>{format(metric.home)}</span><i>–</i><span>{format(metric.away)}</span></section>; })}</div></div>} {match.expertDeviation && <div className="deviation"><Gem size={15}/><span><b>Intressant expertavvikelse · {match.expertDeviation.sign}</b>Expertstödet är {match.expertDeviation.difference} procentenheter högre än strecken.</span></div>}</article>;
}
