import { useEffect, useMemo, useState } from 'react';
import { CheckCircle2, Crown, LockKeyhole, Medal, Sparkles, Swords, Target, Trophy, UserRoundCheck, X, XCircle } from 'lucide-react';
import { claimRound, lockClaimRound, saveChallengerTip, unlockClaimRound } from '../services/firebase';
import type { ClaimRound, LiveStatus, Participant, Round, Sign, Tip } from '../types';

const participants: Participant[] = ['Jocke', 'Tony', 'Gustav', 'Anders', 'Matta-Råsnygg', 'Christer'];
const signs: Sign[] = ['1', 'X', '2'];
const challengerMaxRows = 12;
const orderTip = (values: Sign[]) => signs.filter((sign) => values.includes(sign)).join('') as Tip;
const rowsFor = (tips: Tip[]) => tips.reduce((total, tip) => total * tip.length, 1);

function ChosenSystem({ round, tips }: { round: Round; tips: Array<Tip | ''> }) {
  return <details className="chosen-system">
    <summary>Visa tipsarens valda rad</summary>
    <div className="chosen-system-grid">{round.matches.map((match, index) => <div key={match.matchNumber}>
      <i>{match.matchNumber}</i>
      <span><b>{match.homeTeam}</b><small>{match.awayTeam}</small></span>
      <em aria-label={`Val: ${tips[index] ?? 'saknas'}`}>{signs.map((sign) => <strong className={tips[index]?.includes(sign) ? 'picked' : ''} key={sign}>{sign}</strong>)}</em>
    </div>)}</div>
  </details>;
}

function ChallengerPanel({ round, claim, onChanged }: { round: Round; claim: ClaimRound; onChanged: () => Promise<void> }) {
  const eligible = participants.filter((name) => name !== claim.participant); const existing = claim.challengers ?? {};
  const [participant, setParticipant] = useState<Participant>(eligible[0] ?? 'Jocke'); const [password, setPassword] = useState(''); const [busy, setBusy] = useState(false); const [error, setError] = useState('');
  const [tips, setTips] = useState<Array<Tip | ''>>(() => Array(13).fill(''));
  const complete = tips.every(Boolean); const rows = complete ? rowsFor(tips as Tip[]) : 0; const saved = Object.values(existing).filter(Boolean);
  const chooseParticipant = (name: Participant) => { setParticipant(name); setTips(Array(13).fill('')); setPassword(''); setError(''); };
  const toggle = (index: number, sign: Sign) => setTips((current) => current.map((tip, position) => { if (position !== index) return tip; const values = signs.filter((item) => tip.includes(item)); if (values.includes(sign)) return values.length === 1 ? tip : orderTip(values.filter((item) => item !== sign)); return orderTip([...values, sign]); }));
  const save = async () => { if (!complete) return; setBusy(true); setError(''); try { await saveChallengerTip(claim.roundDate, participant, 'blank', [], tips as Tip[], password); setPassword(''); await onChanged(); } catch (value) { setError(value instanceof Error ? value.message.replace('Firebase: ', '') : 'Utmanartipset kunde inte sparas'); } finally { setBusy(false); } };
  return <section className="challenger-panel"><header><Swords/><div><small>Veckans tävling</small><h3>Besserwissern</h3></div><b>{saved.length}/5</b></header>
    {saved.length > 0 && <div className="challenger-list">{saved.map((entry) => <div key={entry!.participant}><strong>{entry!.participant}</strong><span>{entry!.rows} rader</span><small>{entry!.base === 'blank' ? 'Blank rad' : entry!.base === 'chaparral' ? 'High Chaparall' : 'Experterna'}</small></div>)}</div>}
    <details><summary>{saved.length ? 'Sätt ett utmanartips' : 'Sätt första utmanartipset'}</summary><div className="challenger-form"><label>Utmanare<select value={participant} onChange={(event) => chooseParticipant(event.target.value as Participant)}>{eligible.map((name) => <option key={name}>{name}</option>)}</select></label>{existing[participant] ? <div className="sealed-challenger"><LockKeyhole/><strong>Raden publiceras Måndag när resultatet är inne</strong></div> : <><div className="blank-row-note">Blank rad · välj tecken för samtliga 13 matcher</div><div className="claim-editor">{round.matches.map((match, index) => <div key={match.matchNumber}><span>{match.matchNumber}. {match.homeTeam}–{match.awayTeam}</span><div>{signs.map((sign) => <button className={tips[index].includes(sign) ? 'selected' : ''} onClick={() => toggle(index, sign)} key={sign}>{sign}</button>)}</div></div>)}</div><div className={`claim-total ${rows > challengerMaxRows ? 'over' : ''}`}><span>{complete ? <><b>{rows}</b> rader · {rows} kr</> : <b>Fyll alla 13 matcher</b>}</span><small>Max {challengerMaxRows} rader</small></div><ChosenSystem round={round} tips={tips}/><div className="claim-lock"><input type="password" value={password} onChange={(event) => setPassword(event.target.value)} placeholder="Tstipsets lösenord"/><button disabled={busy || !password || !complete || rows > challengerMaxRows} onClick={() => { if (window.confirm(`Lås utmanartipset för ${participant} med ${rows} rader? Tipset kan inte visas eller ändras före resultatet.`)) save(); }}><Swords size={16}/> Lås utmanartips för {participant}</button></div>{error && <div className="claim-error">{error}</div>}</>}</div></details>
  </section>;
}

const sharpTitle = (participant?: Participant) => participant ? `Satt av ${participant}` : 'Claima veckans skarpa rond';

function ResultCelebration({ claim, claims, round, live, onClose }: { claim: ClaimRound; claims: ClaimRound[]; round: Round; live?: LiveStatus; onClose: () => void }) {
  const challengers = Object.values(claim.challengers ?? {}).filter((entry) => entry?.result).sort((a, b) => b!.result!.payout - a!.result!.payout || b!.result!.maxCorrect - a!.result!.maxCorrect || a!.participant.localeCompare(b!.participant, 'sv'));
  const best = challengers[0]?.result; const winners = best ? challengers.filter((entry) => entry!.result!.payout === best.payout && entry!.result!.maxCorrect === best.maxCorrect) : [];
  const sharpMessage = claim.result!.maxCorrect >= 13 ? 'Tretton rätt – fullträff!' : claim.result!.maxCorrect >= 10 ? 'Stark skarp rond!' : 'Resultatet är inne!';
  const official = claim.officialResult; const liveMatches = live?.roundDate === claim.roundDate ? live.matches : [];
  const sharpStandings = participants.map((name) => { const entries = claims.filter((entry) => entry.status === 'settled' && entry.participant === name && entry.result); return { name, rounds: entries.length, best: entries.reduce((highest, entry) => Math.max(highest, entry.result!.maxCorrect), 0), average: entries.length ? entries.reduce((sum, entry) => sum + entry.result!.maxCorrect, 0) / entries.length : 0, payout: entries.reduce((sum, entry) => sum + entry.result!.payout, 0) }; }).filter((entry) => entry.rounds).sort((a, b) => b.best - a.best || b.payout - a.payout || b.average - a.average || a.name.localeCompare(b.name, 'sv'));
  return <div className="result-modal-backdrop" role="presentation" onMouseDown={(event) => { if (event.target === event.currentTarget) onClose(); }}><section className="result-modal" role="dialog" aria-modal="true" aria-labelledby="result-modal-title"><button className="result-modal-close" type="button" aria-label="Stäng resultat" onClick={onClose}><X/></button><div className="result-modal-hero"><span><Sparkles/></span><small>Omgången är avgjord</small><h2 id="result-modal-title">{sharpMessage}</h2><p>{claim.roundDate} · Omgång {claim.drawNumber}</p></div>
    <div className="result-modal-sharp-table"><header><Crown/><div><small>Skarpa ronden</small><h3>Totalställning</h3></div></header>{sharpStandings[0] && <div className="sharp-leader"><Crown/><span><small>Bästa enskilda skarpa rond</small><strong>{sharpStandings[0].name}</strong></span><em>{sharpStandings[0].best}<small>rätt som bäst</small></em></div>}<div className="sharp-ranking">{sharpStandings.map((entry, index) => <div className={index === 0 ? 'leader' : ''} key={entry.name}><b>{index + 1}</b><span><strong>{entry.name}</strong><small>{entry.rounds} skarpa ronder · {entry.average.toFixed(1)} i snitt</small></span><em>{entry.best} rätt</em><i>{entry.payout.toLocaleString('sv-SE')} kr</i></div>)}</div></div>
    <div className="result-modal-challenge"><header><Trophy/><div><small>Veckans</small><h3>Besserwisser</h3></div></header>{winners.length > 0 && <div className="result-winner"><Medal/><span><strong>{winners.map((entry) => entry!.participant).join(' & ')}</strong><small>{best!.maxCorrect} rätt · {best!.payout.toLocaleString('sv-SE')} kr</small></span></div>}<div className="result-podium">{challengers.map((entry, index) => <div className={index === 0 ? 'winner' : ''} key={entry!.participant}><b>{index + 1}</b><span>{entry!.participant}</span><em>{entry!.result!.maxCorrect} rätt</em></div>)}</div>{challengers.length > 0 && <details className="result-challenger-rows"><summary>Visa alla utmanarrader</summary>{challengers.map((entry) => <div key={entry!.participant}><strong>{entry!.participant}</strong><span>{entry!.finalTips!.map((tip, index) => { const hit = official?.outcomes[index] && tip.includes(official.outcomes[index]); return <i className={hit ? 'hit' : 'miss'} key={index}><small>{index + 1}</small>{tip}</i>; })}</span></div>)}</details>}</div>
    <div className="result-modal-sharp"><Target/><div><small>Skarpa ronden · {claim.rows} rader</small><strong>{claim.participant}</strong></div><em>{claim.result!.maxCorrect}<small>rätt</small></em><b>{claim.result!.payout.toLocaleString('sv-SE')} kr</b></div>
    <details className="result-modal-facts"><summary><span><small>Komplett facit</small><strong>Visa matchresultat och utdelning</strong></span><b>{claim.result!.maxCorrect} rätt</b></summary><div className="result-modal-matches">{round.matches.map((match, index) => { const outcome = official?.outcomes[index] ?? liveMatches[index]?.currentSign; const picked = claim.finalTips?.[index]; const hit = Boolean(outcome && picked?.includes(outcome)); const liveMatch = liveMatches.find((entry) => entry.matchNumber === match.matchNumber); return <div className={hit ? 'hit' : 'miss'} key={match.matchNumber}><b>{match.matchNumber}</b><span><strong>{match.homeTeam} – {match.awayTeam}</strong><small>{liveMatch?.homeScore !== undefined ? `${liveMatch.homeScore}–${liveMatch.awayScore}` : outcome ?? '–'}</small></span><em>Rad {picked}</em>{hit ? <CheckCircle2/> : <XCircle/>}</div>; })}</div>{official && <div className="result-modal-payouts"><small>Officiell utdelning</small>{[13,12,11,10].map((level) => <span key={level}><b>{level} rätt</b><em>{(official.payouts[String(level) as '10'|'11'|'12'|'13'] ?? 0).toLocaleString('sv-SE')} kr</em><i>{claim.result!.winningRows[String(level)] ?? 0} egna rader</i></span>)}</div>}</details>
  </section></div>;
}

export function ClaimPanel({ round, claim, claims, live, onChanged }: { round: Round; claim?: ClaimRound; claims: ClaimRound[]; live?: LiveStatus; onChanged: () => Promise<void> }) {
  const [participant, setParticipant] = useState<Participant>('Jocke'); const [password, setPassword] = useState(''); const [busy, setBusy] = useState(false); const [error, setError] = useState('');
  const [unlockOpen, setUnlockOpen] = useState(false);
  const [resultOpen, setResultOpen] = useState(false);
  const [base, setBase] = useState<'expert' | 'chaparral'>('expert');
  const expertTips = useMemo(() => round.matches.map((match) => match.systemTip), [round]); const chaparralTips = useMemo(() => round.highChaparral?.tips ?? expertTips, [round, expertTips]); const [tips, setTips] = useState<Tip[]>(expertTips);
  useEffect(() => setTips(base === 'expert' ? expertTips : chaparralTips), [base, expertTips, chaparralTips]);
  useEffect(() => { if (claim?.participant) setParticipant(claim.participant); }, [claim?.participant]);
  useEffect(() => { if (!resultOpen) return; const close = (event: KeyboardEvent) => { if (event.key === 'Escape') setResultOpen(false); }; window.addEventListener('keydown', close); return () => window.removeEventListener('keydown', close); }, [resultOpen]);
  if (!claim) return null;
  const rows = rowsFor(tips); const systemsReady = claim.roundDate === round.roundDate;
  const act = async (action: () => Promise<void>) => { setBusy(true); setError(''); try { await action(); setPassword(''); await onChanged(); } catch (value) { setError(value instanceof Error ? value.message.replace('Firebase: ', '') : 'Något gick fel'); } finally { setBusy(false); } };
  const toggle = (index: number, sign: Sign) => setTips((current) => current.map((tip, position) => { if (position !== index) return tip; const values = signs.filter((item) => tip.includes(item)); if (values.includes(sign)) return values.length === 1 ? tip : orderTip(values.filter((item) => item !== sign)); return orderTip([...values, sign]); }));
  return <section className="claim-panel"><header><span className="claim-icon"><UserRoundCheck/></span><div><small>Veckans skarpa rond</small><h2>{sharpTitle(claim.participant)}</h2></div>{claim.status === 'locked' ? <button className="claim-status locked" type="button" aria-expanded={unlockOpen} onClick={() => setUnlockOpen((open) => !open)}><LockKeyhole size={12}/> Låst</button> : claim.status === 'settled' ? <div className="claim-result-actions"><span className="claim-status settled">Avgjord</span><button type="button" onClick={() => setResultOpen(true)}><Trophy size={14}/> Visa resultat</button></div> : <span className={`claim-status ${claim.status}`}>{claim.status === 'unclaimed' ? 'Ledig' : 'Utkast'}</span>}</header>
    {claim.status === 'unclaimed' && <div className="claim-form"><label>Välj tipsare<select value={participant} onChange={(event) => setParticipant(event.target.value as Participant)}>{participants.map((name) => <option key={name}>{name}</option>)}</select></label><label>Gruppens lösenord<input type="password" value={password} onChange={(event) => setPassword(event.target.value)} placeholder="Tstipsets lösenord"/></label><button disabled={busy || !password} onClick={() => act(() => claimRound(claim.roundDate, participant, password))}>Claima omgången</button></div>}
    {claim.status === 'claimed' && <><div className="claim-owner"><label>Ansvarig tipsare<select value={participant} onChange={(event) => setParticipant(event.target.value as Participant)}>{participants.map((name) => <option key={name}>{name}</option>)}</select></label><small>Namnet sparas när raden låses.</small></div>{!systemsReady ? <div className="claim-wait">Expertsystemen blir valbara efter fredagens ordinarie körning.</div> : <><div className="base-picker"><button className={base === 'expert' ? 'active' : ''} onClick={() => setBase('expert')}>Experternas system</button><button className={base === 'chaparral' ? 'active' : ''} onClick={() => setBase('chaparral')}>High Chaparall</button></div><div className="claim-editor">{round.matches.map((match, index) => <div key={match.matchNumber}><span>{match.matchNumber}. {match.homeTeam}–{match.awayTeam}</span><div>{signs.map((sign) => <button className={tips[index].includes(sign) ? 'selected' : ''} onClick={() => toggle(index, sign)} key={sign}>{sign}</button>)}</div></div>)}</div><div className={`claim-total ${rows > 300 ? 'over' : ''}`}><span><b>{rows}</b> rader · {rows} kr</span><small>Max 300 rader</small></div><ChosenSystem round={round} tips={tips}/><div className="claim-lock"><input type="password" value={password} onChange={(event) => setPassword(event.target.value)} placeholder="Bekräfta med Tstipsets lösenord"/><button disabled={busy || !password || rows > 300} onClick={() => { if (window.confirm(`Lås ${rows} rader för ${participant}? Raden kan inte ändras utan en säker upplåsning.`)) act(() => lockClaimRound(claim.roundDate, participant, base, base === 'expert' ? expertTips : chaparralTips, tips, password)); }}><LockKeyhole size={16}/> Lås och skicka in</button></div></>}
    </>}
    {(claim.status === 'locked' || claim.status === 'settled') && <>{systemsReady && claim.finalTips && <ChosenSystem round={round} tips={claim.finalTips}/>} {claim.status === 'locked' && unlockOpen && <div className="unlock-claim"><div><label>Ansvarig tipsare<select value={participant} onChange={(event) => setParticipant(event.target.value as Participant)}>{participants.map((name) => <option key={name}>{name}</option>)}</select></label><label>Gruppens lösenord<input type="password" value={password} onChange={(event) => setPassword(event.target.value)} placeholder="Tstipsets lösenord"/></label><button disabled={busy || !password} onClick={() => { if (window.confirm('Lås upp omgången för korrigering? Den måste låsas igen före spelstopp.')) act(() => unlockClaimRound(claim.roundDate, participant, password)); }}>Lås upp till utkast</button></div><small>Fungerar endast före spelstopp. Den låsta raden tas bort och måste bekräftas på nytt.</small></div>}{claim.status === 'locked' && systemsReady && <ChallengerPanel round={round} claim={claim} onChanged={onChanged}/>}</>}{resultOpen && claim.status === 'settled' && claim.result && <ResultCelebration claim={claim} claims={claims} round={round} live={live} onClose={() => setResultOpen(false)}/>} {error && <div className="claim-error">{error}</div>}
  </section>;
}

export function ParticipantResults({ claims }: { claims: ClaimRound[] }) {
  const settled = claims.filter((claim) => claim.status === 'settled' && claim.participant && claim.result);
  if (!settled.length) return <section className="participant-results"><header><Trophy/><div><small>Tipsgruppen</small><h2>Deltagarresultat</h2></div></header><p>Resultattabellen fylls på efter den första claimade och avgjorda omgången.</p></section>;
  const latest = settled[0];
  const sharpEntries = settled.map((claim) => ({ roundDate: claim.roundDate, participant: claim.participant!, rows: claim.rows!, tips: claim.finalTips!, result: claim.result! }));
  const challengersFor = (claim: ClaimRound) => Object.values(claim.challengers ?? {}).filter((entry) => entry?.result).map((entry) => ({ roundDate: claim.roundDate, participant: entry!.participant, rows: entry!.rows, tips: entry!.finalTips!, result: entry!.result! }));
  const latestChallengers = challengersFor(latest).sort((a, b) => b.result.payout - a.result.payout || b.result.maxCorrect - a.result.maxCorrect || a.participant.localeCompare(b.participant, 'sv'));
  const challengerWins = new Map<Participant, number>();
  settled.forEach((claim) => { const ranked = challengersFor(claim).sort((a, b) => b.result.payout - a.result.payout || b.result.maxCorrect - a.result.maxCorrect); if (!ranked.length) return; const winners = ranked.filter((entry) => entry.result.payout === ranked[0].result.payout && entry.result.maxCorrect === ranked[0].result.maxCorrect); winners.forEach((entry) => challengerWins.set(entry.participant, (challengerWins.get(entry.participant) ?? 0) + 1)); });
  const challengerStandings = participants.map((name) => { const entries = settled.flatMap(challengersFor).filter((entry) => entry.participant === name); return { name, rounds: entries.length, wins: challengerWins.get(name) ?? 0, average: entries.length ? entries.reduce((sum, entry) => sum + entry.result.maxCorrect, 0) / entries.length : 0, payout: entries.reduce((sum, entry) => sum + entry.result.payout, 0) }; }).filter((entry) => entry.rounds).sort((a, b) => b.wins - a.wins || b.payout - a.payout || b.average - a.average);
  const sharpStandings = participants.map((name) => { const entries = sharpEntries.filter((entry) => entry.participant === name); return { name, rounds: entries.length, best: entries.reduce((highest, entry) => Math.max(highest, entry.result.maxCorrect), 0), average: entries.length ? entries.reduce((sum, entry) => sum + entry.result.maxCorrect, 0) / entries.length : 0, payout: entries.reduce((sum, entry) => sum + entry.result.payout, 0) }; }).filter((entry) => entry.rounds).sort((a, b) => b.best - a.best || b.payout - a.payout || b.average - a.average);
  const latestSharp = sharpEntries[0];
  return <section className="participant-results"><header><Trophy/><div><small>Tipsgruppen</small><h2>Resultat</h2></div></header>
    <div className="result-track sharp-track"><small>Skarpa ronden · {latest.roundDate}</small><h3>Huvudsystemets resultat</h3><div className="sharp-result"><span><strong>{latestSharp.participant}</strong><small>Ansvarig tipsare · {latestSharp.rows} rader</small></span><em>{latestSharp.result.maxCorrect} rätt</em><i>{latestSharp.result.payout.toLocaleString('sv-SE')} kr</i></div><details className="published-rows"><summary>Visa den skarpa raden</summary><div><strong>{latestSharp.participant}</strong><span>{latestSharp.tips.map((tip, index) => <i key={index}><small>{index + 1}</small>{tip}</i>)}</span></div></details></div>
    <div className="standings-title"><small>Endast ansvariga tipsare · bästa enskilda omgång</small><h3>Historik – skarpa ronder</h3></div><div className="standings sharp-standings">{sharpStandings.map((entry, index) => <div key={entry.name}><span>{index + 1}</span><strong>{entry.name}</strong><small>{entry.rounds} skarpa · {entry.average.toFixed(1)} i snitt</small><b>{entry.best} rätt som bäst</b><em>{entry.payout.toLocaleString('sv-SE')} kr</em></div>)}</div>
    <div className="result-track challenger-track"><small>Besserwissern · {latest.roundDate}</small><h3>Veckans utmanartips</h3>{latestChallengers.length ? latestChallengers.map((entry, index) => <div className="challenger-result" key={entry.participant}><b>{index + 1}</b><span><strong>{entry.participant}</strong><small>Utmanare · {entry.rows} rader</small></span><em>{entry.result.maxCorrect} rätt</em><i>{entry.result.payout.toLocaleString('sv-SE')} kr</i></div>) : <p>Inga utmanartips registrerades för omgången.</p>} {latestChallengers.length > 0 && <details className="published-rows"><summary>Visa utmanarnas publicerade rader</summary>{latestChallengers.map((entry) => <div key={entry.participant}><strong>{entry.participant}</strong><span>{entry.tips.map((tip, index) => <i key={index}><small>{index + 1}</small>{tip}</i>)}</span></div>)}</details>}</div>
    <div className="standings-title"><small>Endast utmanartips</small><h3>Totalställning – Besserwissern</h3></div><div className="standings">{challengerStandings.map((entry, index) => <div key={entry.name}><span>{index + 1}</span><strong>{entry.name}</strong><small>{entry.rounds} utmanartips</small><b>{entry.wins} segrar · {entry.average.toFixed(1)} rätt</b><em>{entry.payout.toLocaleString('sv-SE')} kr</em></div>)}</div>
    <details><summary>Visa tidigare skarpa ronder</summary><div className="result-rounds">{sharpEntries.map((entry) => <div key={entry.roundDate}><span>{entry.roundDate}</span><strong>{entry.participant}</strong><small>Skarp rond · {entry.result.maxCorrect} rätt</small><b>{entry.result.payout.toLocaleString('sv-SE')} kr</b></div>)}</div></details>
  </section>;
}
