import { useEffect, useMemo, useState } from 'react';
import { LockKeyhole, Swords, Trophy, UserRoundCheck } from 'lucide-react';
import { claimRound, lockClaimRound, saveChallengerTip, unlockClaimRound } from '../services/firebase';
import type { ClaimRound, Participant, Round, Sign, Tip } from '../types';

const participants: Participant[] = ['Jocke', 'Tony', 'Gustav', 'Anders', 'Matta-Råsnygg', 'Christer'];
const signs: Sign[] = ['1', 'X', '2'];
const challengerMaxRows = 12;
const orderTip = (values: Sign[]) => signs.filter((sign) => values.includes(sign)).join('') as Tip;
const rowsFor = (tips: Tip[]) => tips.reduce((total, tip) => total * tip.length, 1);

function ChosenSystem({ round, tips }: { round: Round; tips: Array<Tip | ''> }) {
  return <details className="chosen-system">
    <summary>Visa tipsarens valda rad</summary>
    <div className="chosen-system-grid">{round.matches.map((match, index) => <div key={match.matchNumber}>
      <i>{match.matchNumber}</i>
      <span><b>{match.homeTeam}</b><small>{match.awayTeam}</small></span>
      <em aria-label={`Val: ${tips[index] ?? 'saknas'}`}>{signs.map((sign) => <strong className={tips[index]?.includes(sign) ? 'picked' : ''} key={sign}>{sign}</strong>)}</em>
    </div>)}</div>
  </details>;
}

function ChallengerPanel({ round, claim, onChanged }: { round: Round; claim: ClaimRound; onChanged: () => Promise<void> }) {
  const eligible = participants.filter((name) => name !== claim.participant); const existing = claim.challengers ?? {};
  const [participant, setParticipant] = useState<Participant>(eligible[0] ?? 'Jocke'); const [password, setPassword] = useState(''); const [busy, setBusy] = useState(false); const [error, setError] = useState('');
  const [tips, setTips] = useState<Array<Tip | ''>>(() => Array(13).fill(''));
  const complete = tips.every(Boolean); const rows = complete ? rowsFor(tips as Tip[]) : 0; const saved = Object.values(existing).filter(Boolean);
  const chooseParticipant = (name: Participant) => { setParticipant(name); setTips(existing[name]?.finalTips ?? Array(13).fill('')); };
  const toggle = (index: number, sign: Sign) => setTips((current) => current.map((tip, position) => { if (position !== index) return tip; const values = signs.filter((item) => tip.includes(item)); if (values.includes(sign)) return values.length === 1 ? tip : orderTip(values.filter((item) => item !== sign)); return orderTip([...values, sign]); }));
  const save = async () => { if (!complete) return; setBusy(true); setError(''); try { await saveChallengerTip(claim.roundDate, participant, 'blank', [], tips as Tip[], password); setPassword(''); await onChanged(); } catch (value) { setError(value instanceof Error ? value.message.replace('Firebase: ', '') : 'Utmanartipset kunde inte sparas'); } finally { setBusy(false); } };
  return <section className="challenger-panel"><header><Swords/><div><small>Veckans tävling</small><h3>Besserwissern</h3></div><b>{saved.length}/5</b></header>
    {saved.length > 0 && <div className="challenger-list">{saved.map((entry) => <div key={entry!.participant}><strong>{entry!.participant}</strong><span>{entry!.rows} rader</span><small>{entry!.base === 'blank' ? 'Blank rad' : entry!.base === 'chaparral' ? 'High Chaparall' : 'Experterna'}</small></div>)}</div>}
    <details><summary>{saved.length ? 'Sätt eller ändra utmanartipset' : 'Sätt första utmanartipset'}</summary><div className="challenger-form"><label>Utmanare<select value={participant} onChange={(event) => chooseParticipant(event.target.value as Participant)}>{eligible.map((name) => <option key={name}>{name}</option>)}</select></label><div className="blank-row-note">Blank rad · välj tecken för samtliga 13 matcher</div><div className="claim-editor">{round.matches.map((match, index) => <div key={match.matchNumber}><span>{match.matchNumber}. {match.homeTeam}–{match.awayTeam}</span><div>{signs.map((sign) => <button className={tips[index].includes(sign) ? 'selected' : ''} onClick={() => toggle(index, sign)} key={sign}>{sign}</button>)}</div></div>)}</div><div className={`claim-total ${rows > challengerMaxRows ? 'over' : ''}`}><span>{complete ? <><b>{rows}</b> rader · {rows} kr</> : <b>Fyll alla 13 matcher</b>}</span><small>Max {challengerMaxRows} rader</small></div><ChosenSystem round={round} tips={tips}/><div className="claim-lock"><input type="password" value={password} onChange={(event) => setPassword(event.target.value)} placeholder="Tstipsets lösenord"/><button disabled={busy || !password || !complete || rows > challengerMaxRows} onClick={() => { if (window.confirm(`Lås ${participant}s utmanartips med ${rows} rader?`)) save(); }}><Swords size={16}/> {existing[participant] ? 'Uppdatera utmanartips' : 'Lås utmanartips'}</button></div>{error && <div className="claim-error">{error}</div>}</div></details>
  </section>;
}

const sharpTitle = (participant?: Participant) => participant ? `Satt av ${participant}` : 'Claima veckans skarpa rond';

export function ClaimPanel({ round, claim, onChanged }: { round: Round; claim?: ClaimRound; onChanged: () => Promise<void> }) {
  const [participant, setParticipant] = useState<Participant>('Jocke'); const [password, setPassword] = useState(''); const [busy, setBusy] = useState(false); const [error, setError] = useState('');
  const [unlockOpen, setUnlockOpen] = useState(false);
  const [base, setBase] = useState<'expert' | 'chaparral'>('expert');
  const expertTips = useMemo(() => round.matches.map((match) => match.systemTip), [round]); const chaparralTips = useMemo(() => round.highChaparral?.tips ?? expertTips, [round, expertTips]); const [tips, setTips] = useState<Tip[]>(expertTips);
  useEffect(() => setTips(base === 'expert' ? expertTips : chaparralTips), [base, expertTips, chaparralTips]);
  useEffect(() => { if (claim?.participant) setParticipant(claim.participant); }, [claim?.participant]);
  if (!claim) return null;
  const rows = rowsFor(tips); const systemsReady = claim.roundDate === round.roundDate;
  const act = async (action: () => Promise<void>) => { setBusy(true); setError(''); try { await action(); setPassword(''); await onChanged(); } catch (value) { setError(value instanceof Error ? value.message.replace('Firebase: ', '') : 'Något gick fel'); } finally { setBusy(false); } };
  const toggle = (index: number, sign: Sign) => setTips((current) => current.map((tip, position) => { if (position !== index) return tip; const values = signs.filter((item) => tip.includes(item)); if (values.includes(sign)) return values.length === 1 ? tip : orderTip(values.filter((item) => item !== sign)); return orderTip([...values, sign]); }));
  return <section className="claim-panel"><header><span className="claim-icon"><UserRoundCheck/></span><div><small>Veckans skarpa rond</small><h2>{sharpTitle(claim.participant)}</h2></div>{claim.status === 'locked' ? <button className="claim-status locked" type="button" aria-expanded={unlockOpen} onClick={() => setUnlockOpen((open) => !open)}><LockKeyhole size={12}/> Låst</button> : <span className={`claim-status ${claim.status}`}>{claim.status === 'unclaimed' ? 'Ledig' : claim.status === 'claimed' ? 'Utkast' : 'Avgjord'}</span>}</header>
    {claim.status === 'unclaimed' && <div className="claim-form"><label>Välj tipsare<select value={participant} onChange={(event) => setParticipant(event.target.value as Participant)}>{participants.map((name) => <option key={name}>{name}</option>)}</select></label><label>Gruppens lösenord<input type="password" value={password} onChange={(event) => setPassword(event.target.value)} placeholder="Tstipsets lösenord"/></label><button disabled={busy || !password} onClick={() => act(() => claimRound(claim.roundDate, participant, password))}>Claima omgången</button></div>}
    {claim.status === 'claimed' && <><div className="claim-owner"><label>Ansvarig tipsare<select value={participant} onChange={(event) => setParticipant(event.target.value as Participant)}>{participants.map((name) => <option key={name}>{name}</option>)}</select></label><small>Namnet sparas när raden låses.</small></div>{!systemsReady ? <div className="claim-wait">Expertsystemen blir valbara efter fredagens ordinarie körning.</div> : <><div className="base-picker"><button className={base === 'expert' ? 'active' : ''} onClick={() => setBase('expert')}>Experternas system</button><button className={base === 'chaparral' ? 'active' : ''} onClick={() => setBase('chaparral')}>High Chaparall</button></div><div className="claim-editor">{round.matches.map((match, index) => <div key={match.matchNumber}><span>{match.matchNumber}. {match.homeTeam}–{match.awayTeam}</span><div>{signs.map((sign) => <button className={tips[index].includes(sign) ? 'selected' : ''} onClick={() => toggle(index, sign)} key={sign}>{sign}</button>)}</div></div>)}</div><div className={`claim-total ${rows > 300 ? 'over' : ''}`}><span><b>{rows}</b> rader · {rows} kr</span><small>Max 300 rader</small></div><ChosenSystem round={round} tips={tips}/><div className="claim-lock"><input type="password" value={password} onChange={(event) => setPassword(event.target.value)} placeholder="Bekräfta med Tstipsets lösenord"/><button disabled={busy || !password || rows > 300} onClick={() => { if (window.confirm(`Lås ${rows} rader för ${participant}? Raden kan inte ändras utan en säker upplåsning.`)) act(() => lockClaimRound(claim.roundDate, participant, base, base === 'expert' ? expertTips : chaparralTips, tips, password)); }}><LockKeyhole size={16}/> Lås och skicka in</button></div></>}
    </>}
    {(claim.status === 'locked' || claim.status === 'settled') && <>{systemsReady && claim.finalTips && <ChosenSystem round={round} tips={claim.finalTips}/>} {claim.status === 'locked' && unlockOpen && <div className="unlock-claim"><div><label>Ansvarig tipsare<select value={participant} onChange={(event) => setParticipant(event.target.value as Participant)}>{participants.map((name) => <option key={name}>{name}</option>)}</select></label><label>Gruppens lösenord<input type="password" value={password} onChange={(event) => setPassword(event.target.value)} placeholder="Tstipsets lösenord"/></label><button disabled={busy || !password} onClick={() => { if (window.confirm('Lås upp omgången för korrigering? Den måste låsas igen före spelstopp.')) act(() => unlockClaimRound(claim.roundDate, participant, password)); }}>Lås upp till utkast</button></div><small>Fungerar endast före spelstopp. Den låsta raden tas bort och måste bekräftas på nytt.</small></div>}{claim.status === 'locked' && systemsReady && <ChallengerPanel round={round} claim={claim} onChanged={onChanged}/>}</>}{error && <div className="claim-error">{error}</div>}
  </section>;
}

export function ParticipantResults({ claims }: { claims: ClaimRound[] }) {
  const settled = claims.filter((claim) => claim.status === 'settled' && claim.participant && claim.result);
  if (!settled.length) return <section className="participant-results"><header><Trophy/><div><small>Tipsgruppen</small><h2>Deltagarresultat</h2></div></header><p>Resultattabellen fylls på efter den första claimade och avgjorda omgången.</p></section>;
  const entriesFor = (claim: ClaimRound) => [{ participant: claim.participant!, role: 'Skarp rond', rows: claim.rows!, result: claim.result! }, ...Object.values(claim.challengers ?? {}).filter((entry) => entry?.result).map((entry) => ({ participant: entry!.participant, role: 'Utmanare', rows: entry!.rows, result: entry!.result! }))];
  const weekly = entriesFor(settled[0]).sort((a, b) => b.result.payout - a.result.payout || b.result.maxCorrect - a.result.maxCorrect || a.participant.localeCompare(b.participant, 'sv'));
  const wins = new Map<Participant, number>(); settled.forEach((claim) => { const ranked = entriesFor(claim).sort((a, b) => b.result.payout - a.result.payout || b.result.maxCorrect - a.result.maxCorrect); const winners = ranked.filter((entry) => entry.result.payout === ranked[0].result.payout && entry.result.maxCorrect === ranked[0].result.maxCorrect); winners.forEach((entry) => wins.set(entry.participant, (wins.get(entry.participant) ?? 0) + 1)); });
  const standings = participants.map((name) => { const entries = settled.flatMap(entriesFor).filter((entry) => entry.participant === name); return { name, rounds: entries.length, wins: wins.get(name) ?? 0, average: entries.length ? entries.reduce((sum, entry) => sum + entry.result.maxCorrect, 0) / entries.length : 0, payout: entries.reduce((sum, entry) => sum + entry.result.payout, 0) }; }).filter((entry) => entry.rounds).sort((a, b) => b.wins - a.wins || b.payout - a.payout || b.average - a.average);
  return <section className="participant-results"><header><Trophy/><div><small>Tipsgruppen</small><h2>Rondmästerskapet</h2></div></header><div className="weekly-result"><small>Senaste avgjorda tävlingen · {settled[0].roundDate}</small><h3>Veckans resultat</h3>{weekly.map((entry, index) => <div className={entry.role === 'Skarp rond' ? 'sharp' : ''} key={entry.participant}><b>{index + 1}</b><span><strong>{entry.participant}</strong><small>{entry.role}</small></span><em>{entry.result.maxCorrect} rätt</em><i>{entry.result.payout.toLocaleString('sv-SE')} kr</i></div>)}</div><div className="standings-title"><small>Alla avgjorda ronder</small><h3>Totalställning</h3></div><div className="standings">{standings.map((entry, index) => <div key={entry.name}><span>{index + 1}</span><strong>{entry.name}</strong><small>{entry.rounds} tips</small><b>{entry.wins} segrar · {entry.average.toFixed(1)} rätt</b><em>{entry.payout.toLocaleString('sv-SE')} kr</em></div>)}</div><details><summary>Visa tidigare tävlingar</summary><div className="result-rounds">{settled.map((claim) => <div key={claim.roundDate}><span>{claim.roundDate}</span><strong>{claim.participant}</strong><small>Skarp rond · {claim.result!.maxCorrect} rätt</small><b>{claim.result!.payout.toLocaleString('sv-SE')} kr</b></div>)}</div></details></section>;
}
